### ISSUE TITLE
Linking ST to config file / clonal complex

### ISSUE THREAD

**Issue by BertBog** [phe-bioinformatics/snapperdb_references#1]
Hello,

Thanks for making these references and configurations available, it has really helped us with the implementation of SnapperDB at our institute. 

As the documentation recommends to use SnapperDB at the clonal complex level, we were wondering how to obtain the clonal complex for all of our isolates. Our current approach is to perform MLST using the 7-gene Warwick scheme (from EnteroBase) to obtain the sequence type. As far as we know EnteroBase does not provide the corresponding clonal complex for each sequence type, so we used this database by DTU to get the clonal complex: (https://bitbucket.org/genomicepidemiology/mlst_db/src/ac4d272773605bc240151b05155d63a674a53b31/ecoli.clpx). But we noticed that this database had 'None' as clonal complex for a lot of our samples. So my questions related to that are the following.

- What do you do when there is no clonal complex associated with the detected sequence type (or when this information is unknown)?
- Related to the first question, how do you link the sequence type to the clonal complex?
- I noticed that there some of the config files with the O-type in the name, are they decisions rules to decide when the config file is selected based on CC and when it is selected based on O-type?

Best regards,
Bert 

P.S. I was not sure whether I should post this issue in this repo or in the main SnapperDB repo, so if this is the wrong place I will post it in the other one.

**Comment by timdallman** [comment]
Hi Bert.
As SnapperDB relies on reference based SNP calling you need to use an appropriate “close” reference – i.e within ~10K SNPs from the reference genome.
MLST clonal complex is a good proxy for this.  As you note clonal complex is not uniformly defined for species so for this case we would use a reference from the same ST.
Unfortunately the configs for E.coli are not very consistently name but all work at the clonal complex level.
We use a JSON lookup to direct isolates to the correct snapperdb based on the ST results (attached).

 e.g. for E.coli O157 – here are the list of STs associated with CC11.
 "('11','1595','587','1804','1833','2966','3254','P3029','1825','P3030','P3031','P3181','P3202','P3210','P3211','P3215','P3217', '3297', 'P3286', '6956')": "CC11",
later in the JSON we declare that CC11 is associated with the snapperdb O157_snps

Hope helpful
Best wishes
Tim
